
version: 2

models:
  - name: dim_aircraft
    description: "aircraft dimension model"
    columns:
      - name: aircraft_code
        description: "The primary key for this table"
        data_tests:
          - not_null


  - name: dim_airport
    description: "airport dimension model"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null